AWSTemplateFormatVersion: '2010-09-09'
Description: >
  (__SOLUTION_ID__) - __SOLUTION_NAME__ __VERSION__ - publisher and subscriber shared resources for asset exchange.

Outputs:

  SubscriberOnboardingSummary:
    Description: Configuration information for subscriber.
    Value:
      Fn::Join:
        - ' '
        - - Fn::Sub: PUBLISHER_NAME=${PublisherName}
          - Fn::Sub: SUBSCRIBER_NAME=${SubscriberName}
          - Fn::Sub: AWS_REGION=${AWS::Region}
          - Fn::Sub: BUCKET_NAME=${ExchangeBucket}
          - Fn::Join:
            - '='
            - - SUBSCRIBER_ROLE
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role

  ConsoleUrl:
    Description: Use this url to directly access the shared bucket.
    Value:
      Fn::Sub: https://s3.console.aws.amazon.com/s3/buckets/${ExchangeBucket}/?region=${AWS::Region}&tab=overview

  PublisherOnboardingSummary:
    Description: Configuration information for publisher.
    Value:
      Fn::Join:
        - ' '
        - - Fn::Sub: PUBLISHER_NAME=${PublisherName}
          - Fn::Sub: SUBSCRIBER_NAME=${SubscriberName}
          - Fn::Sub: AWS_REGION=${AWS::Region}
          - Fn::Sub: BUCKET_NAME=${ExchangeBucket}
          - Fn::Sub: KMS_KEY_ARN=${CMK.Arn}
          - Fn::Sub: EVENT_SOURCE_NAME=mxc-${AWS::Region}-${Environment}-publisher
          - Fn::Join:
            - ''
            - - LOG_BUCKET_NAME=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-logs
          - Fn::Join:
            - ''
            - - SUBSCRIBER_CANONICAL_USER_ID=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-canonicalid
          - Fn::Join:
            - '='
            - - PUBLISHER_ROLE
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role

Metadata:

  License:
    Description: |
        Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

        Licensed under the Apache License, Version 2.0 (the "License").
        You may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Deployment Configuration"
        Parameters:
          - Environment
      -
        Label:
          default: "Agreement Configuration"
        Parameters:
          - PublisherName
          - SubscriberName
          - ExpirationInDays
          - Notifications


Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev
    AllowedPattern: "[A-Za-z0-9]+"
    ConstraintDescription: Malformed input-Parameter MyParameter must only contain uppercase and lowercase letters and numbers
    MaxLength: 10
    MinLength: 2

  PublisherName:
    Type: String
    Description: The name of the publisher, case sensitive, as registered in this Media Exchange deployment.
    ConstraintDescription: Malformed input-Parameter PublisherName must only contain uppercase and lowercase letters and numbers
    MaxLength: 64
    MinLength: 3

  SubscriberName:
    Type: String
    Description: The name of the subscriber, case sensitive, as registered in this Media Exchange deployment.
    AllowedPattern: "[A-Za-z0-9]+"
    ConstraintDescription: Malformed input-Parameter SubscriberName must only contain uppercase and lowercase letters and numbers
    MaxLength: 64
    MinLength: 3

  ExpirationInDays:
    Type: Number
    Description: The assets get lifecycle deleted after these many days from the MediaExchange bucket.
    MinValue: 3
    Default: 10

  Notifications:
    Type: String
    Description: Select yes to forward all S3 notifications.
    Default: "no"
    AllowedValues:
      - "yes"
      - "no"

Conditions:
  EnableS3Notifications:
    Fn::Equals:
    - "yes"
    - Ref: Notifications

Resources:

  ExchangeBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W41
            reason: "(W41) S3 Bucket should have encryption option set"

    Properties:

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      VersioningConfiguration:
        Status: Enabled

      LoggingConfiguration:
        LogFilePrefix:
          Fn::Sub: logs/${SubscriberName}/
        DestinationBucketName:
          Fn::ImportValue:
            Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-logs

      #Expire objects after the lifecycle period
      LifecycleConfiguration:
        Rules:
          -
            Id: Expire
            Status: Enabled
            ExpirationInDays:
              Ref: ExpirationInDays

          -
            Id: AutoRemove
            Status: Enabled
            NoncurrentVersionExpirationInDays:
              Ref: ExpirationInDays

          -
            Id: CleanupIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2

      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event: 's3:ObjectCreated:*'
            Function:
              Fn::GetAtt: S3EventForwarderFunction.Arn


    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    DependsOn: LambdaPermissionForS3Bucket


  #bucket policy
  ExchangeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ExchangeBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          # TLS only
          -
            Sid: "RequireTLS"
            Action:
              - "s3:*"
            Effect: "Deny"
            Resource:
              - Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
            Principal: "*"
            Condition:
              Bool:
                aws:SecureTransport: false

          # # require KMS for put
          -
            Sid: "DenyIncorrectEncryptionHeader"
            Action:
              - "s3:PutObject"
            Effect: "Deny"
            Resource:
              - Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
            Principal: "*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: aws:kms

          -
            Sid: "DenyBucketOwnerFullControl"
            Action:
              - "s3:PutObject"
            Effect: "Deny"
            Resource:
              - Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
            Principal: "*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

          ## Need to specify the KMS Key Id
          -
            Sid: "DenyNoCMKHeader"
            Action:
              - "s3:PutObject"
            Effect: "Deny"
            Resource:
              - Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
            Principal: "*"
            Condition:
              'Null':
                s3:x-amz-server-side-encryption-aws-kms-key-id: true

          -
            Sid: "AllowCopyOpPublisher"
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetObjectAcl
              - s3:GetObjectVersionAcl
              - s3:GetObjectTagging
              - s3:GetObjectVersionTagging
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:DeleteObject
              - s3:DeleteObjectTagging
              - s3:DeleteObjectVersion
              - s3:DeleteObjectVersionTagging
            Resource:
              Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
            Principal:
              AWS:
                - Fn::ImportValue:
                    Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role

          # read permissions are granted by the ACLs. In addition we want the tags to be private.
          # -
          #   Sid: "AllowCopyOpSubscriber"
          #   Effect: Allow
          #   Action:
          #     - s3:GetObject
          #     - s3:GetObjectVersion
          #     - s3:GetObjectAcl
          #     - s3:GetObjectVersionAcl
          #     - s3:GetObjectTagging
          #     - s3:GetObjectVersionTagging
          #   Resource:
          #     Fn::Sub: arn:aws:s3:::${ExchangeBucket}/*
          #   Principal:
          #     AWS:
          #       - Fn::ImportValue:
          #           Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role

          -
            Sid: "AllowBasicConsole"
            Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              Fn::Sub: arn:aws:s3:::${ExchangeBucket}
            Principal:
              AWS:
                - Fn::ImportValue:
                    Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role
                - Fn::ImportValue:
                    Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role



  CMK:
    Type: AWS::KMS::Key
    Properties:
      Description: Symetric Key for Encrypting Objects in Media Exchange
      Enabled: true
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: node-key-policy
        Statement:
          -
            Sid: KeyManagement
            Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'
          -
            Sid: SubscriberAccess
            Effect: Allow
            Principal:
              AWS:
                Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role

            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: '*'
          -
            Sid: PublisherAccess
            Effect: Allow
            Principal:
              AWS:
                Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:ListAliases
            Resource: '*'


  LambdaPermissionForS3Bucket:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: S3EventForwarderFunction
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId

  S3NotifySubscriberRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Notify Content Published"
      EventPattern:
        source:
          - mxc.s3
        detail-type:
          - Fn::Sub: bucket=${ExchangeBucket}
      State:
        Fn::If:
          - EnableS3Notifications
          - "ENABLED"
          - "DISABLED"
      Targets:
        -
          Id: "SNSEvent"
          InputPath: $.detail
          Arn:
            Fn::ImportValue:
              Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-notificationtopic
          DeadLetterConfig:
            Arn:
              Fn::ImportValue:
                Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-notificationdlq

  NotifySubscriberRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Notify Publisher Messages"
      EventPattern:
        source:
          - mxc.publisher
        detail-type:
          - Fn::Sub: bucket=${ExchangeBucket}
      State: "ENABLED"
      Targets:
        -
          Id: "SNSEvent"
          InputPath: $.detail
          Arn:
            Fn::ImportValue:
              Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-notificationtopic
          DeadLetterConfig:
            Arn:
              Fn::ImportValue:
                Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-notificationdlq


  S3EventForwarderFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Role for EventForwarer Lambda.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: mxc-lambda-putevents
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  Fn::Sub: arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default

  #lambda to send s3 events to EventBus
  S3EventForwarderFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to forward the S3 event notifications to EventBridge
      MemorySize: 128
      Role:
        Fn::GetAtt: S3EventForwarderFunctionRole.Arn
      Runtime: python3.7
      Timeout: 10
      Handler: index.handler
      Environment:
        Variables:
          LogLevel: INFO

      Code:
        ZipFile: |
          import os
          import logging
          import boto3
          import json

          logger = logging.getLogger()
          logger.setLevel(os.environ['LogLevel'])

          #events client
          client = boto3.client('events')

          def handler(event, context):
            try:
              logger.info("forwarding Event to EventBridge")

              bucket = event["Records"][0]["s3"]["bucket"]["name"]
              logger.debug(bucket)
              detail = json.dumps(event)
              logger.debug(detail)

              response = client.put_events(
                Entries=[
                    {
                        'Source': "mxc.s3",
                        'DetailType': "bucket="+bucket,
                        'Detail': detail
                    },
                ]
              )

              logger.debug("finished forwarding event")

            except Exception as e:
                # Catch all exceptions
                result = 'Exception: {}'.format(e)
                logger.error(result)
