AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cloudformation template to setup publisher in media exchange.

Outputs:

  PublisherRole:
    Description: Publisher's S3 Access role
    Value:
      Fn::If:
        - HasRole
        - Ref: PublisherRole
        - Fn::Sub: arn:aws:iam::${PublisherAccountId}:root
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role

Metadata:

  License:
    Description: |
        Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

        Licensed under the Apache License, Version 2.0 (the "License").
        You may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Deployment Configuration"
        Parameters:
          - Environment
      -
        Label:
          default: "Publisher Configuration"
        Parameters:
          - PublisherName
          - PublisherAccountId
          - PublisherRole

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev

  PublisherName:
    Type: String
    Description: Name of the publisher

  PublisherAccountId:
    Type: String
    Description: The AWS accountId of the publisher. This parameter is ignored if you specify PublisherRole.

  PublisherRole:
    Description: Publisher's Role. Defaults to arn:aws:iam::$PublisherAccountId:root.
    Type: String
    Default: ''

Conditions:
  HasRole:
    Fn::Not:
      - Fn::Equals:
        - ""
        - Ref: PublisherRole


Resources:

  PutEventsPermission:
    Type: AWS::Events::EventBusPolicy
    Properties:
      Action:
        events:PutEvents
      Principal:
        Ref: PublisherAccountId
      StatementId:
        Fn::Sub: "Sid${PublisherName}${Environment}Events"
