AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Cloudformation template for MediaSync.


Outputs:
  LambdaFunctionArn:
    Description: LambdaFunctionArn to use with S3 batch
    Value:
      Fn::GetAtt: MediaSyncDriverFunction.Arn
  S3BatchRoleArn:
    Description: IAM Role for to use with S3 batch
    Value:
      Fn::GetAtt: MediaSyncS3BatchRole.Arn
  FlowLogBucketName:
    Description: "Flow log Bucket Name"
    Value: !Ref FlowLogBucket
Metadata:

  License:
    Description: |
        Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

        Licensed under the Apache License, Version 2.0 (the "License").
        You may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Deployment Configuration"
        Parameters:
          - Environment
          - ImageName
      -
        Label:
          default: "Copy Configuration"
          Parameters:
            - BucketOwnerFullControl
            - DestinationBucketName

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev
    AllowedPattern: "[A-Za-z0-9]+"
    ConstraintDescription: Malformed input-Parameter Environment must only contain uppercase and lowercase letters and numbers
    MaxLength: 10
    MinLength: 2

  ImageName:
    Type: String
    Description: Image Name
    Default: amazon/aws-cli

  BucketOwnerFullControl:
    Type: String
    AllowedValues: ["Yes", "No"]
    Description: Select "Yes" to provide full access to copied objects. Select "No" for no access.
    Default: "Yes"

  DestinationBucketName:
    Type: String
    Description: Destination S3 Bucket Name

Conditions:
  IsBucketOwnerFullControl:
    Fn::Equals:
      - "Yes"
      - Ref: BucketOwnerFullControl

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
       - Key: Name
         Value: mediasync

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the EC2 instances launched into the VPC by Batch
      VpcId:
        Ref: VPC

  SecurityGroupIngress:
   Type: AWS::EC2::SecurityGroupIngress
   Properties:
    GroupId: !Ref SecurityGroup
    IpProtocol: -1
    SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId

  SubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""

  SubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId:
        Ref: VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""

  SubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      VpcId:
        Ref: VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: ""

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC

  SubnetRouteTableAssociationOne:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetOne

  SubnetRouteTableAssociationTwo:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetTwo

  SubnetRouteTableAssociationThree:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: SubnetThree

  FlowLogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          -
            Id: Expire
            Status: Enabled
            Transitions:
              -
                StorageClass: GLACIER
                TransitionInDays: 90

  FlowLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FlowLogBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          # TLS only
          -
            Sid: "RequireTLS"
            Action:
              - "s3:*"
            Effect: "Deny"
            Resource:
              - Fn::Sub: arn:aws:s3:::${FlowLogBucket}/*
            Principal: "*"
            Condition:
              Bool:
                aws:SecureTransport: false

          -
            Sid: "AWSLogDeliveryWrite"
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              Fn::Sub: arn:aws:s3:::${FlowLogBucket}/flow-logs/AWSLogs/*
            Principal:
              Service: delivery.logs.amazonaws.com
            Condition:
              StringEquals:
                's3:x-amz-acl' : bucket-owner-full-control

          -
            Sid: "AWSLogDeliveryAclCheck"
            Effect: Allow
            Action:
              - s3:GetBucketAcl
            Resource:
              Fn::Sub: arn:aws:s3:::${FlowLogBucket}
            Principal:
              Service: delivery.logs.amazonaws.com

  VPCLogDeliveringToS3:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId:
        Ref: VPC
      ResourceType: VPC
      TrafficType: ALL
      LogDestination:
        Fn::GetAtt: FlowLogBucket.Arn
      LogDestinationType: s3
      MaxAggregationInterval: 60

  MediaSyncJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      ComputeEnvironmentOrder:
        -
          Order: 1
          ComputeEnvironment:
            Ref: MediaSyncSPOTComputeEnvironment


  MediaSyncSPOTComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole:
        Fn::GetAtt: BatchServiceRole.Arn

      ComputeResources:
        Type: FARGATE_SPOT
        MaxvCpus: 48 # 48x 64 == 3072 < 3500 (number of concurrent PUT requests per prefix.)
        Subnets:
          - Ref: SubnetOne
          - Ref: SubnetTwo
          - Ref: SubnetThree

        SecurityGroupIds:
          - Ref: SecurityGroup

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: batch.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole


  MediaSyncDriverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to be invoked by s3 batch
      CodeUri: lambda/driver/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Sid: batch
            Effect: Allow
            Action:
              - batch:SubmitJob
              - batch:DescribeJobs
              - batch:TerminateJob
            Resource:
            - Fn::Sub: arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-definition/*
            - Fn::Sub: arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-queue/*
          - Sid: batchList
            Effect: Allow
            Action:
              - batch:ListJobs
              - batch:TagResource
            Resource: '*'

        - Statement:
          - Sid: S3
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetObjectAcl
              - s3:GetObjectVersionAcl
              - s3:GetObjectTagging
              - s3:GetObjectVersionTagging
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
            Resource: '*'
          - Sid: kms
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'

      Timeout: 300
      ReservedConcurrentExecutions: 256

      Environment:
        Variables:
          JOB_DEFINITION:
            Ref: CopyJobDefinition
          JOB_QUEUE:
            Ref: MediaSyncJobQueue
          DESTINATION_BUCKET_NAME:
            Ref: DestinationBucketName
          IS_BUCKET_OWNER_FULL_CONTROL: !If [IsBucketOwnerFullControl, 'TRUE', 'FALSE']
          DISABLE_PENDING_JOBS_CHECK: true
          MAX_NUMBER_OF_PENDING_JOBS: 96 #== 2x of MaxvCpus
          MN_SIZE_FOR_BATCH_IN_BYTES: 524288000 #500MB - this optimizaed for cost. Set it to 5GB for optimal speed.
          LogLevel: INFO

  CopyJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image:
          Fn::Sub: ${ImageName}

        ExecutionRoleArn:
          Fn::GetAtt: ExecutionRole.Arn

        FargatePlatformConfiguration:
          PlatformVersion: 1.4.0
        NetworkConfiguration:
          AssignPublicIp: ENABLED

        ResourceRequirements:
          -
            Type: VCPU
            Value: 1
          -
            Type: MEMORY
            Value: 2048

        Command:
          # - aws
          - s3
          - cp
          - Ref::SourceS3Uri
          - Ref::DestinationS3Uri
          - --copy-props
          - default
          - --expected-size
          - Ref::Size
          - !If [ IsBucketOwnerFullControl, '--acl bucket-owner-full-control', !Ref 'AWS::NoValue']

        JobRoleArn:
          Fn::GetAtt: JobRole.Arn

      RetryStrategy:
        Attempts: 3
        # TODO inspect exit codes for throttles
        #  only retry for 1, and 255


  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  JobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action:
            - sts:AssumeRole
      Policies:
        -
          PolicyName: KMSAndS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectTagging
                  - s3:GetObjectVersionTagging
                  - s3:ListBucket
                Resource: '*'
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectTagging
                  - s3:GetObjectVersionTagging
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:PutObjectVersionAcl
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionTagging
                Resource:
                  Fn::Sub: arn:aws:s3:::${DestinationBucketName}/*

              -
                Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: '*'

  MediaSyncS3BatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: batchoperations.s3.amazonaws.com
        Version: "2012-10-17"
      Path: /
      Policies:
        -
          PolicyName: S3BatchRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetObjectAcl
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectTagging
                  - s3:GetObjectVersionTagging
                  - s3:PutObject
                  - lambda:InvokeFunction
                Effect: Allow
                Resource: '*'
              -
                Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: '*'
