AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Cloudformation template for media exchange cross account access roles.

Outputs:
  ProducerRole:
    Description: Producer Role
    Value:
      Fn::GetAtt: XAccountRole.Arn

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev
  ProducerAccountId:
    Type: String
    Description: The accountId of the producer.
    # TODO: Regex
  Email:
    Type: String
    Description: The email address of the producer.
    # TODO: Regex

Resources:

  XAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Cross accont role for mxc
      RoleName: 
        Fn::Sub: mxc-producer-${Environment}-${AWS::Region}-${AWS::AccountId}-${ProducerAccountId}
      
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                Ref: ProducerAccountId
            Action: 'sts:AssumeRole'
            # Condition:
            #   StringEquals:
            #     'sts:ExternalId':
            #       Ref: Email
      Path: /
      Policies:
        -
          PolicyName: mxc-producer-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Resource: '*'
              -
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:Get*
                Resource:
                  Fn::Sub: arn:aws:s3:::mxc-store-${Environment}-${AWS::Region}-${AWS::AccountId}
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  Fn::Sub: arn:aws:s3:::mxc-store-${Environment}-${AWS::Region}-${AWS::AccountId}/*
              # -
              #   Effect: Allow
              #   Action:
              #     - sns:ListSubscriptions
              #   Resource: '*'
              -
                Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:mxc-topic-${Environment}-${AWS::Region}-${AWS::AccountId}-*

  
